### ISSUE TITLE
The chess pieces are not moving on touch devices (tablets and smartphones)

### ISSUE THREAD

**Issue by sudeshchouhan** [LabinatorSolutions/BoldChess-Stockfish-Web-GUI#1]
@LabinatorSolutions 
Hi, I have found solution for the issue.
In the file "chessboard-caustique-min.js", search **$(this).context.id**, it is trying to get the id of the clicked piece.
It is using "context" but context is depreciated in JQuery version 3.0 and onward.
See https://api.jquery.com/context/
So now it's not able to get id of the clicked piece.
Solution is that simply replace **$(this).context.id** with **this.id** or **$(this).attr("id")**
I am new to GitHub. Please someone update the chessboard-caustique-min.js as i suggested.

Please note that this is a library by https://github.com/caustique/chessboard-js
It would be great if someone fix the bug there also.

**Comment by LabinatorSolutions** [comment]
Thank you @sudeshchouhan for your contribution and welcome to GitHub!
The issue has been fixed already based on your comment.

The repository at (https://github.com/caustique/chessboard-js) is totally inactive. The last commit was 6 years ago. The maintainer of that repository might not be interested to maintain the project anymore. We will do our best!

If you like to contribute more to this open source project, please check the main page for the list of remaining issues and possible improvements.

All the best!
