### ISSUE TITLE
The flip functionality on touch devices is not working

### ISSUE THREAD

**Issue by LabinatorSolutions** [LabinatorSolutions/BoldChess-Stockfish-Web-GUI#2]
The "caustique" chessboard is not rotating/flipping on touch devices (tablets and smartphones). This affects the "flip" and the "switch sides" buttons.

**Comment by IPetak** [comment]
Fixed, also made a pull request. :)

**Comment by LabinatorSolutions** [comment]
Great work Ivan! Thank you!
