### ISSUE TITLE
Cannot start game as Black on touch devices

### ISSUE THREAD

**Issue by LabinatorSolutions** [LabinatorSolutions/BoldChess-Stockfish-Web-GUI#3]
The user can not start a new game with the black pieces if he/she is on touch devices (tablets and smartphones). The only way for the computer to play as White is if the user has clicked the "Switch Sides" button.

**Comment by IPetak** [comment]
Fixed this also! :)

**Comment by LabinatorSolutions** [comment]
Hi Ivan!

Thank you very much for your time and contribution to this Chess GUI. You did a great job.

All your pull requests have been approved.

All the best!
