### ISSUE TITLE
The "Show Hint" button is not working for the Black pieces on touch devices

### ISSUE THREAD

**Issue by LabinatorSolutions** [LabinatorSolutions/BoldChess-Stockfish-Web-GUI#4]
The "Show Hint" button is not working on touch devices (tablets and smartphones).

- For the White pieces - Fixed by @IPetak 
- For the Black pieces - Not Fixed Yet - Currently Unassigned.

**Comment by IPetak** [comment]
Made a pull request with fix! :)

**Comment by LabinatorSolutions** [comment]
Hi Ivan!

Thank you for your work and contribution.

I have already accepted your pull request. **However, the "Show Hint" button is now suggesting an invalid move for the Black pieces when playing on touch devices (Smartphones & Tablets).**

I will keep this issue open until we find a resolution.

Thank you once again for your time and all your work. Your name has already been added to our contributors' list.

All the best!

**Comment by IPetak** [comment]
Feel free to assign this issue to me, I'll try to fix it so it works for both.

**Comment by LabinatorSolutions** [comment]
Thank you Ivan for your interest to improve this free open-source GUI.

The issue has been assigned to you but you are free to work on it whenever you have free time and are in the mood for this.

**Comment by IPetak** [comment]
You're welcome, It's a fun project to help with. So I've made a new PR with the fix, the button "show hint" should work for both sides regardless if the board if flipped or not.

**Comment by LabinatorSolutions** [comment]
Great work! It is working very well now.
Thank you for all your work, time, and contribution to this FOSS project.
